// Aakash Shrestha — site content

window.PROFILE = {
  name: "Aakash Shrestha",
  location: "Miami, FL",
  email: "shresthaaakash678@gmail.com",
  phone: "786-553-0235",
  github: "https://github.com/aakashxtha",
  linkedin: "https://www.linkedin.com/in/aakashshrestha395/",

  oneLiner: "Computational protein design, molecular dynamics, and research software.",

  tagline: "I turn molecular questions into simulations, and simulations into answers.",

  about: `I like figuring out how molecules work by putting them in simulations. My background is biomedical engineering, but most of my time goes to computational biophysics: protein design, molecular dynamics, and the code that connects them. These days I'm running large enzyme simulations as a modeling intern at the National Laboratory of the Rockies, and getting ready to start a PhD in Fall 2027.`,

  personal: "Trained as a biomedical engineer, I found my home where protein design, molecular simulation, and code all meet.",

  homeCta: "Thanks for stopping by! Feel free to wander through my projects and the molecules I've modeled.",

  homeModels: ["tem1-design-44A", "cellulose-graphene", "circRNA51"],

  updated: "June 2026",

  motd: [
    "tip: type `projects` to see what I've been building.",
    "currently: validating a stress-granule engine I wrote from scratch.",
    "tip: try `open sbxat` to jump straight to my latest work.",
    "fun fact: most of these structures render live from rcsb.org.",
    "tip: `random` loads a random structure — go poke at a protein.",
  ],

  proteinFacts: [
    "Your body runs on roughly 20,000 different proteins right now, tiny machines doing almost everything.",
    "A protein is just a chain of building blocks that folds into a 3D shape, and that shape is everything.",
    "Spider silk is a protein that's tougher, pound for pound, than steel.",
    "Some proteins fold into their final shape in less than a millionth of a second.",
    "The 'spike' protein is how the COVID virus pries its way into your cells.",
    "Enzymes are proteins that speed up chemistry millions of times. Without them, digesting a meal could take years.",
    "Your hair, nails, and skin are mostly built from a single protein: keratin.",
    "When proteins fold the wrong way, you can get diseases like Alzheimer's and ALS.",
    "One red blood cell carries about 270 million copies of hemoglobin, the protein that makes blood red.",
    "Predicting how a protein folds stumped scientists for 50 years. AI only cracked it recently.",
    "Venom, antibodies, and muscle are all proteins: same toolkit, wildly different jobs.",
    "Designing a brand-new protein from scratch used to be science fiction. Now it's a Tuesday.",
  ],

  highlightedTools: ["RFdiffusion", "ProteinMPNN", "Latent-X", "PyRosetta"],

  statusTools: ["AMBER", "CHARMM", "GROMACS", "NAMD", "Python", "MATLAB", "HPC"],

  skills: {
    "molecular_dynamics": ["AMBER", "CHARMM", "GROMACS", "NAMD", "MARTINI", "VMD", "PyMOL", "SLURM", "GPU HPC"],
    "protein_design": ["RFdiffusion", "ProteinMPNN", "Latent-X", "PyRosetta", "Rosetta", "AlphaFold", "Boltz-2"],
    "programming": ["Python", "MATLAB", "Jupyter", "C++", "Bash", "Git", "Linux", "HPC"],
    "wet_lab": ["PCR", "Gel Electrophoresis", "Western Blot", "Spectrophotometry", "HPLC"],
  },

  experience: [
    {
      id: "nlr",
      company: "National Laboratory of the Rockies",
      role: "Molecular Modeling Intern",
      location: "Golden, CO · Remote",
      period: "Nov 2025 — present",
      bullets: [
        "Ran large-scale MD on plant glycosyltransferase SbXAT to explain how a single mutation switches sugar donor preference; manuscript submitted for publication.",
        "Building an MD model of formate dehydrogenase on a gold electrode to see how the enzyme sits on the surface and stays stable.",
        "Combined the protein, electrode, and coating into one system, including custom parameters for the metal centers.",
      ],
    },
    {
      id: "umiami",
      company: "University of Miami",
      role: "Research Associate I",
      location: "Miami, FL",
      period: "Aug 2025 — Nov 2025",
      bullets: [
        "Built MATLAB tools with five independent ways to classify crystal vs. dissolved ions in NaCl trajectories.",
        "Designed a local safe-spheres method to measure concentration near the crystal–solution interface without boundary contamination.",
        "Checked methods against each other; matching experimental solubility exactly is still open.",
      ],
    },
    {
      id: "fiu",
      company: "Computational Biophysics Lab, FIU",
      role: "Research Assistant",
      location: "Miami, FL",
      period: "Apr 2022 — Apr 2025",
      bullets: [
        "Ran the full macrocyclic peptide pipeline for VP40, from backbone generation through shortlisting 20+ candidates for synthesis.",
        "Rewrote the lab's MD job scripts for failures and checkpointing, improving throughput by about 40%.",
        "Turned messy cellulose composite building scripts into a tested Python package I used for my own models.",
      ],
    },
    {
      id: "rosetta",
      company: "Rosetta Commons",
      role: "Rosetta REU Intern",
      location: "Tempe, AZ",
      period: "Jun 2024 — Aug 2024",
      bullets: [
        "Built pyrotini, a pipeline linking PyRosetta design, GROMACS/MARTINI simulation, and flexibility analysis to screen 500+ TEM-1 variants.",
        "Parallelized jobs to cut per-variant runtime from hours to minutes.",
        "Presented at RosettaCon 2024.",
      ],
    },
    {
      id: "nrel",
      company: "National Renewable Energy Laboratory",
      role: "Student Training in Applied Research (STAR) Intern",
      location: "Golden, CO",
      period: "May 2023 — Jul 2023",
      bullets: [
        "Set up nylon 6,6 and 6,10 MD models from crystal structures, my first serious polymer simulation work.",
        "Found a parameterization issue that destabilized runs around 30 ns; eventually reached stable 100 ns trajectories.",
        "Documented the setup for whoever picks it up next.",
      ],
    },
  ],

  projects: [
    {
      id: "fdh",
      title: "FDH Enzyme on Gold Electrode",
      kicker: "National Laboratory of the Rockies",
      affiliation: "Golden, CO · Remote · Nov 2025 — present",
      category: "protein",
      status: "ongoing",
      hook: "Modeling an enzyme on a gold electrode for biosensors and biofuel cells.",
      summary: "I'm modeling formate dehydrogenase attached to a gold electrode coated with a self-assembled monolayer (SAM), to see how the enzyme settles onto the SAM and whether it stays stable once it's bound. That behavior is what decides whether enzymes like this can work in biosensors and biofuel cells.",
      highlights: [
        "Combined the protein, electrode, and SAM into one working simulation system",
        "Built custom parameters for the enzyme's metal centers, which standard tools don't handle",
        "Placed and oriented the protein on the SAM, then ran simulations and started analyzing the results",
      ],
      metrics: [
        { label: "Enzyme", value: "Formate dehydrogenase" },
        { label: "Goal", value: "Stability on electrode" },
        { label: "Stage", value: "Analyzing results" },
      ],
      tags: ["Molecular Dynamics", "Bioelectrochemistry", "Metalloproteins"],
      relatedModels: [],
      year: "2025",
    },
    {
      id: "sbxat",
      title: "SbXAT Donor Specificity Switch",
      kicker: "National Laboratory of the Rockies",
      affiliation: "Golden, CO · Remote · 2025",
      category: "protein",
      status: "completed",
      featured: true,
      hook: "Explained an enzyme's sugar-specificity switch at atomic resolution; manuscript submitted.",
      summary: "At NLR I studied SbXAT, a plant enzyme that adds sugars to hemicellulose in the cell wall. Collaborators had shown that a single mutation makes it prefer a different sugar donor; I used MD to explain why at the atomic level. I simulated wild-type and mutant with both donors, built an analysis pipeline, and traced the switch to a new hydrogen bond that only shows up when the mutant binds xylose. We submitted a manuscript for publication.",
      highlights: [
        "Ran ~3 µs of MD across four enzyme–donor combinations on NREL HPC",
        "Built a Python/MDAnalysis pipeline for stability, hydrogen bonds, and active-site contacts",
        "Identified a new hydrogen bond with xylose that explains the experimentally observed specificity switch",
      ],
      metrics: [
        { label: "Simulation time", value: "~3 µs" },
        { label: "Systems", value: "4 enzyme–ligand pairs" },
        { label: "Publication", value: "Manuscript submitted" },
      ],
      tags: ["NAMD", "CHARMM", "MDAnalysis", "Python", "HPC"],
      relatedModels: [],
      relatedPdb: "9OIS",
      year: "2025",
    },
    {
      id: "nacl",
      title: "NaCl Crystallization Analysis",
      kicker: "University of Miami",
      affiliation: "Miami, FL · Aug — Nov 2025",
      category: "materials",
      status: "completed",
      hook: "Five independent methods to measure NaCl solubility from MD trajectories.",
      summary: "Computational chemistry work on how NaCl crystallizes out of water. I built MATLAB tools to pull the equilibrium solubility out of existing simulation data, which is a hard number to measure because there's no clean line between the crystal and the dissolved ions around it.",
      highlights: [
        "Wrote five independent ways to tell crystal ions apart from dissolved ones, then checked them against each other",
        "Used graph theory to classify ions by how they connect, an unusual angle for this kind of problem",
        "Methods agree with each other; pinning the exact solubility against experiment is still open",
      ],
      metrics: [
        { label: "Classification methods", value: "5" },
        { label: "System scale", value: "~27k atoms" },
        { label: "Toolkit scripts", value: "25+" },
      ],
      tags: ["MATLAB", "MD Analysis", "Graph Theory", "OVITO", "VMD"],
      relatedModels: [],
      year: "2025",
    },
    {
      id: "macrocycle",
      title: "Macrocyclic Peptide Design — VP40",
      kicker: "FIU Computational Biophysics Lab",
      affiliation: "Miami, FL · 2022 — present",
      category: "protein",
      status: "ongoing",
      hook: "Designed cyclic peptide binders against the Ebola matrix protein VP40; now being synthesized.",
      summary: "At FIU I worked on cyclic peptides meant to bind VP40, the Ebola virus matrix protein. I ran the pipeline myself: generating backbones, assigning sequences, screening with MD, and picking candidates to send to synthesis. Those compounds are being made in the lab now.",
      highlights: [
        "Ran the full pipeline from design through shortlisting candidates for the bench",
        "Tried 12 macrocycle ring sizes at different binding sites on VP40",
        "Moved 20+ candidates forward; synthesis and binding tests are underway",
      ],
      metrics: [
        { label: "Macrocycle sizes", value: "12 lengths" },
        { label: "Top candidates", value: "20+" },
        { label: "Experimental validation", value: "Ongoing" },
      ],
      tags: ["RFdiffusion", "ProteinMPNN", "Latent-X", "NAMD", "VMD", "Python"],
      relatedModels: [],
      year: "ongoing",
    },
    {
      id: "tem1",
      title: "TEM-1 Design Pipeline",
      kicker: "Rosetta Commons REU",
      affiliation: "Tempe, AZ · Summer 2024",
      category: "protein",
      status: "completed",
      hook: "One pipeline to design and screen 500+ enzyme variants; open-sourced as pyrotini.",
      summary: "During my Rosetta REU I built one workflow that chains PyRosetta design, GROMACS/MARTINI simulation, and flexibility analysis for TEM-1 β-lactamase. Before that, each step lived in a different tool and had to be run by hand. I screened 500+ variants with it; the code is on GitHub as pyrotini.",
      highlights: [
        "Linked PyRosetta, GROMACS/MARTINI, and flexibility analysis into a single repeatable pipeline",
        "Screened 500+ variants; parallel jobs cut runtime from hours to minutes per variant",
        "Put pyrotini on GitHub so others can run the same workflow",
      ],
      metrics: [
        { label: "Variants screened", value: "500+" },
        { label: "Per-variant runtime", value: "hours → minutes" },
        { label: "Reference structure", value: "PDB 1BTL" },
      ],
      tags: ["Python", "PyRosetta", "GROMACS", "MARTINI", "SLURM", "HPC"],
      relatedModels: ["tem1-design-44A"],
      relatedPdb: "1BTL",
      presentation: {
        title: "Computational Design of TEM-1 β-Lactamase Using PyRosetta",
        venue: "RosettaCon 2024",
        where: "Cle Elum, WA",
      },
      year: "2024",
    },
    {
      id: "cellulose",
      title: "Cellulose Nanocomposite Toolkit",
      kicker: "FIU Computational Biophysics Lab",
      affiliation: "Miami, FL · 2022 — 2025",
      category: "composite",
      status: "completed",
      hook: "Turned messy lab scripts into a tested Python package for building nanocomposites.",
      summary: "The lab had a pile of one-off scripts for building cellulose–graphene and cellulose–CNT models. I turned that into a Python package with a CLI and tests so the same structures could be rebuilt without hand-editing files every time. I used it for my own composite models; it's there if the lab wants to adopt it later.",
      highlights: [
        "Replaced manual, error-prone structure building with one automated pipeline",
        "Supports cellulose–graphene, cellulose–CNT, and three-component setups",
        "Added tests so bad geometries get caught before anyone runs long simulations",
      ],
      metrics: [
        { label: "Test coverage", value: ">95%" },
        { label: "Composite configs", value: "3 types" },
        { label: "Output format", value: "PDB" },
      ],
      tags: ["Python", "CLI", "PDB", "Materials Science", "Testing"],
      relatedModels: [
        "cellulose-graphene",
        "cellulose-cnt-graphene",
        "cellulose-20L",
        "cellulose-structure1",
        "cellulose-structure2",
      ],
      year: "2023",
    },
    {
      id: "nylon",
      title: "Polymer Degradation in Nylons",
      kicker: "NREL STAR Internship",
      affiliation: "Golden, CO · Summer 2023",
      category: "polymer",
      status: "completed",
      hook: "First polymer MD project: chased down why nylon trajectories fell apart.",
      summary: "Summer intern project at NREL: my first serious polymer MD setup. I built models of nylon 6,6 and 6,10 from crystal structures and spent a lot of time learning why trajectories fall apart when the force field isn't quite right.",
      highlights: [
        "Set up both nylon 6,6 and 6,10 from crystallographic starting structures",
        "Tracked down a parameterization issue that destabilized runs around 30 ns",
        "Eventually reached stable 100 ns production trajectories and wrote up the setup for the next person",
      ],
      metrics: [
        { label: "Polymer systems", value: "2" },
        { label: "Production length", value: "100 ns" },
        { label: "Force field", value: "CHARMM" },
      ],
      tags: ["GROMACS", "NAMD", "CHARMM", "Python", "HPC"],
      relatedModels: ["nylon66", "nylon610"],
      presentation: {
        title: "From Simulation to Solution: Decoding Nylons",
        venue: "NREL Summer Poster Symposium",
        where: "Golden, CO",
      },
      year: "2023",
    },
    {
      id: "sgsim",
      title: "Stress Granule Simulator (sgsim)",
      kicker: "Personal Project",
      affiliation: "Side project · 2025",
      category: "software",
      status: "ongoing",
      hook: "A GPU simulation engine I wrote from scratch, for fun, to model biomolecular condensates.",
      summary: "A simulation engine I built from scratch on my own time to model how stress granule proteins assemble into biomolecular condensates, the liquid-like droplets that form inside cells. Stress granules are protein–RNA condensates tied to diseases like ALS, and existing tools couldn't handle the parts I cared about, like proteins competing for the same binding sites and switching shape when RNA shows up. So I wrote my own.",
      highlights: [
        "Wrote a GPU simulation engine for protein–RNA phase separation from first principles",
        "Modeled competition between G3BP1, CAPRIN1, USP10, and UBAP2L, plus G3BP1's shape switch on RNA binding",
        "Backed it with 96 tests and analysis dashboards (RDF, MSD, clustering, density profiles)",
      ],
      metrics: [
        { label: "Tests", value: "96" },
        { label: "Target scale", value: "~1000 proteins" },
        { label: "Stage", value: "Engine done; validating" },
      ],
      tags: ["Python", "GPU", "Simulation", "Biophysics", "Testing"],
      relatedModels: [],
      repo: "https://github.com/aakashxtha/sgsim",
      year: "2025",
    },
  ],

  presentations: [
    { title: "Computational Design of TEM-1 β-Lactamase Using PyRosetta", venue: "RosettaCon 2024", where: "Cle Elum, WA", date: "Aug 2024" },
    { title: "From Simulation to Solution: Decoding Nylons", venue: "NREL Summer Poster Symposium", where: "Golden, CO", date: "Jul 2023" },
  ],

  education: {
    school: "Florida International University",
    degree: "B.S. Biomedical Engineering",
    date: "April 2025",
    honors: ["Honors College", "Dean's List (8 semesters)", "GPA 3.94/4.00"],
    coursework: ["Biochemistry", "Genetics", "Molecular Engineering", "Biomaterials", "Engineering Analysis of Biological Systems", "BME Data Analysis"],
  },

  models: [
    {
      id: "tem1-design-44A",
      name: "TEM-1 Res44A Variant",
      type: "protein",
      origin: "Rosetta REU · 2024",
      defaultStyle: "cartoon",
      desc: "One TEM-1 variant from the Rosetta REU screen, with a mutation at residue 44.",
      file: "models/tem1-design-44A.pdb",
    },
    {
      id: "cellulose-graphene",
      name: "Cellulose–Graphene Composite",
      type: "composite",
      origin: "FIU · 2023",
      defaultStyle: "stick",
      desc: "Cellulose sheets with a graphene layer, built with the composite toolkit.",
      file: "models/cellulose-graphene.pdb",
    },
    {
      id: "cellulose-cnt-graphene",
      name: "Cellulose–CNT–Graphene",
      type: "composite",
      origin: "FIU · 2023",
      desc: "Cellulose, a carbon nanotube, and graphene in one three-component model.",
      file: "models/cellulose-cnt-graphene3.pdb",
    },
    {
      id: "cellulose-20L",
      name: "Aligned Cellulose (20-Layer)",
      type: "polymer",
      origin: "FIU · 2023",
      desc: "20-layer aligned cellulose, the baseline before adding graphene or CNT.",
      file: "models/cellulose-20L.pdb",
    },
    {
      id: "cellulose-structure1",
      name: "Cellulose Structure 1",
      type: "polymer",
      origin: "FIU · 2023",
      desc: "One of two cellulose packing setups, used to compare chain arrangements before building composites.",
      file: "models/cellulose-structure1.pdb",
    },
    {
      id: "cellulose-structure2",
      name: "Cellulose Structure 2",
      type: "polymer",
      origin: "FIU · 2023",
      desc: "Second cellulose packing setup, paired with Structure 1 for comparison.",
      file: "models/cellulose-structure2.pdb",
    },
    {
      id: "nylon66",
      name: "Nylon 6,6 Polymer",
      type: "polymer",
      origin: "NREL · 2023",
      desc: "Nylon 6,6 crystal structure from the NREL intern project.",
      file: "models/nylon66.pdb",
    },
    {
      id: "nylon610",
      name: "Nylon 6,10 Crystal",
      type: "polymer",
      origin: "NREL · 2023",
      desc: "Nylon 6,10 crystal, the longer-chain polymer from the same NREL project.",
      file: "models/nylon610.pdb",
    },
    {
      id: "circRNA51",
      name: "Circular RNA (circRNA51)",
      type: "nucleic",
      origin: "FIU · 2023",
      defaultStyle: "stick",
      desc: "Circular RNA structure prepared for a 200 ns MD run.",
      file: "models/circRNA51.pdb",
    },
  ],

  structures: [
    { id: "1BTL", name: "TEM-1 β-Lactamase" },
    { id: "9OIS", name: "SbXAT Glycosyltransferase" },
    { id: "7XQW", name: "Formate Dehydrogenase (FDH)" },
    { id: "1CRN", name: "Crambin" },
    { id: "1UBQ", name: "Ubiquitin" },
    { id: "6VXX", name: "SARS-CoV-2 Spike" },
  ],
};
